# Generated by Django 5.2.7 on 2025-10-21 13:00

import apps.funcionarios.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[apps.funcionarios.models.validar_cpf])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo', models.CharField(max_length=100)),
                ('nivel_acesso', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('vendedor', 'Vendedor'), ('financeiro', 'Financeiro')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
