# Generated by Django 5.2.7 on 2025-11-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuário')], max_length=20),
        ),
    ]
