# Generated by Django 5.2.7 on 2025-10-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email_corporativo', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
