# Generated by Django 5.2.7 on 2025-10-21 06:24

import apps.fornecedores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[apps.fornecedores.validators.validar_cnpj]),
        ),
    ]
