# Generated by Django 5.2.7 on 2025-10-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='contato_comercial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
