# Generated by Django 5.2.7 on 2025-10-21 11:07

import apps.fornecedores.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_alter_fornecedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato de celular inválido. Use (XX) XXXXX-XXXX.', regex='^$?\\d{2}$?\\s?\\d{5}-?\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Formato de CEP inválido. Use 00000-000.', regex='^\\d{5}-\\d{3}$')]),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(help_text='Digite o CNPJ no formato 00.000.000/0000-00', max_length=18, unique=True, validators=[apps.fornecedores.validators.validar_cnpj]),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(default='nao_informado@exemplo.com', max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='E-mail inválido.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato de telefone inválido. Use (XX) XXXXX-XXXX.', regex='^$?\\d{2}$?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
