# Generated by Django 5.2.7 on 2025-10-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_fornecedor_bairro_fornecedor_celular_fornecedor_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
